---
# Playbook to setup folder strucutures for a project
- name: Updating an Ansible Project
  hosts: localhost
  vars_files:
    - "host_vars/localhost.yml"

# This will prompt you to type your project's directory name in the console
  vars_prompt:

    - name: project 
      prompt: Name of project?
      private: False

  tasks:

    # If the project does not already exist, we are going to first create the root folder for your project based on the project name you typed in the prompt above
  - name: Delete Existing Project Directory and Content
    file:
      path: /{{ projects }}/{{ project }}
      state: directory
    delegate_to: localhost

  # This task will copy any updated files or directories in the default directory struture into your existing project folder created above; please use --skip-tags "alt_layout" to apply this layout
  - name: Copy Default Layout Into Your Project
    copy:
      src: /{{ layout }}/
      dest: /{{ projects }}/{{ project }}/
      force: no
    tags:
      - default_layout

  # This task will copy any updated files or directories in the default directory struture into your existing project folder created above; please use --skip-tags "default_layout" to apply this layout
  - name: Copy Alternate Layout Into Your Project
    copy:
      src: /{{ alt_layout }}/
      dest: /{{ projects }}/{{ project }}/
      force: no
    tags:
      - alt_layout
